### PR TITLE
Load test spec at runtime rather than Docker image build time

### PR DESCRIPTION
**Pull request by mtlynch**
If we copy cypress/ and cypress.json into the Docker container at image build time, then the user is forced to rebuild the entire image every time they want to modify their test and re-run Cypress. By loading the test specs as Docker volumes, the user can modify them and then re-run the tests without having to rebuild the image.

This also means that when the tests fail, the artifacts folders are available on the host machine rather than trapped in the Docker container.

### CODE REVIEW

**Comment by spenwall** [comment]
This is awesome, and great timing. I like being able to run new tests without building every time.

**Comment by bahmutov** [comment]
@mtlynch you are a good writer - can you please describe using comments and maybe README how the volume is mapped and how to work with the test runner locally?

**Comment by mtlynch** [comment]
@bahmutov sure thing, updated!

**Comment by bahmutov** [comment]
thank you @mtlynch

**Pull request merged**
